sudo: false
language: node_js
node_js:
- stable
os:
- linux
before_install:
- yarn add global -g @sanity/cli
script:
- sanity && sanity build && ls -la ./dist
branches:
  only:
  - master
  - develop
