sudo: true
language: node_js
node_js:
- stable
os:
- linux
addons:
  ssh_known_hosts: 130.193.54.238
before_install:
- openssl aes-256-cbc -K $encrypted_504078b5b0bc_key -iv $encrypted_504078b5b0bc_iv -in deploy.gpg.enc -out deploy.gpg -d
- gpg --import deploy.gpg
- export TZ=Europe/Moscow
- date
- curl -L https://github.com/minrk/git-crypt-bin/releases/download/0.6.0/git-crypt
  > git-crypt
- echo "128817a63de17a5af03fe69241e453436c6c286c86dd37fb70ed9b3bf7171d7d  git-crypt"
  | shasum -a 256 -c -
- chmod +x git-crypt
- sudo cp git-crypt /usr/local/bin/
- git-crypt unlock
install:
- yarn global add @sanity/cli
script:
- sanity install
- sanity build --no-minify
before_deploy:
-  openssl aes-256-cbc -K $encrypted_504078b5b0bc_key -iv $encrypted_504078b5b0bc_iv -in deploy_rsa.enc -out /temp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist deploy@130.193.54.238:admin
  on:
    branch:
    - master
    - develop
branches:
  only:
  - master
  - develop
