sudo: false
language: node_js
node_js:
  - stable
os:
  - linux
before_install:
  - openssl aes-256-cbc -K $encrypted_504078b5b0bc_key -iv $encrypted_504078b5b0bc_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - export TZ=Europe/Moscow
  - date
  - npm install -g @sanity/cli
script:
    - sanity build
addons:
  ssh_known_hosts: 188.166.58.173
after_success:
   - eval "$(ssh-agent -s)"
   - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
   - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
branches:
  only:
    - master
    - develop
