language: node_js
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_504078b5b0bc_key -iv $encrypted_504078b5b0bc_iv
  -in deploy_rsa.enc -out $TRAVIS_BUILD_DIR/deploy_rsa -d
- export TZ=Europe/Moscow
- date
addons:
  ssh_known_hosts: 188.166.58.173
after_success:
 - eval "$(ssh-agent -s)"
 - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
 - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa