version: '3.7'
services:
  node:
    build:
      context: .
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        PROJECT_ID: ${PROJECT_ID}
        PROJECT_DATASET: ${PROJECT_DATASET}
    env_file:
      - .env
    tty: true
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: ./.config
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./.config/etc/ssl:/etc/nginx/ssl
      - ./.config/etc/admin-moskvatrip-ru.conf:/etc/nginx/service-admin-moskvatrip-ru.conf
      - ./static:/srv/docroot
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=tech-support@nevatrip.ru
      - LE_FQDN=admin.moskvatrip.ru
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
