version: '3.7'

x-project: &function
  image: app_base:1
  command:
    - /bin/sh
    - -c
    - |
      cd /home/node/app && \
      sed -i -e 's/$$NAME/'$$PROJECT_NAME'/g' \
             -e 's/$$PROJECT/'$$PROJECT_ID'/g' \
             -e 's/$$DATASET/'$$PROJECT_DATASET'/g' sanity.json && \
      pm2-runtime ecosystem.config.js
  tty: true
  restart: unless-stopped
  networks:
    - app-network
  
services:
  base:
    build:
      context: .
    image: app_base:1
    tty: true

  nevatrip:
    <<: *function
    environment:
      PROJECT_NAME: ${NEVATRIP_NAME}
      PROJECT_ID: ${NEVATRIP_ID}
      PROJECT_DATASET: ${NEVATRIP_DATASET}

  moskvatrip:
    <<: *function
    environment:
      PROJECT_NAME: ${MOSKVATRIP_NAME}
      PROJECT_ID: ${MOSKVATRIP_ID}
      PROJECT_DATASET: ${MOSKVATRIP_DATASET}

  prahatrip:
    <<: *function
    environment:
      PROJECT_NAME: ${PRAHATRIP_NAME}
      PROJECT_ID: ${PRAHATRIP_ID}
      PROJECT_DATASET: ${PRAHATRIP_DATASET}

  nginx:
    build: ./.config
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./.config/etc/ssl:/etc/nginx/ssl
      - ./.config/etc/admin-moskvatrip-ru.conf:/etc/nginx/service-admin-moskvatrip-ru.conf
      - ./.config/etc/admin-nevatrip-ru.conf:/etc/nginx/service-admin-nevatrip-ru.conf
      - ./.config/etc/admin-prahatrip-cz.conf:/etc/nginx/service-admin-prahatrip-cz.conf
      - ./static:/srv/docroot
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=tech-support@nevatrip.ru
      - LE_FQDN=admin.moskvatrip.ru,admin.nevatrip.ru,admin.prahatrip.cz
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
