version: '3.7'
services:
  nevatrip:
    build:
      context: .
      args:
        PROJECT_NAME: ${NEVATRIP_NAME}
        PROJECT_ID: ${NEVATRIP_ID}
        PROJECT_DATASET: ${NEVATRIP_DATASET}
    image: cr.yandex/${YC_REGISTRY_ID}/admin-nevatrip
    environment:
      PROJECT_NAME: ${NEVATRIP_NAME}
    tty: true
    restart: unless-stopped
    networks:
      - app-network

  moskvatrip:
    build:
      context: .
      args:
        PROJECT_NAME: ${MOSKVATRIP_NAME}
        PROJECT_ID: ${MOSKVATRIP_ID}
        PROJECT_DATASET: ${MOSKVATRIP_DATASET}
    image: cr.yandex/${YC_REGISTRY_ID}/admin-moskvatrip
    environment:
      PROJECT_NAME: ${MOSKVATRIP_NAME}
    tty: true
    restart: unless-stopped
    networks:
      - app-network

  prahatrip:
    build:
      context: .
      args:
        PROJECT_NAME: ${PRAHATRIP_NAME}
        PROJECT_ID: ${PRAHATRIP_ID}
        PROJECT_DATASET: ${PRAHATRIP_DATASET}
    image: cr.yandex/${YC_REGISTRY_ID}/admin-prahatrip
    environment:
      PROJECT_NAME: ${PRAHATRIP_NAME}
    tty: true
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build: ./.config
    image: cr.yandex/${YC_REGISTRY_ID}/admin-nginx
    hostname: nginx
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./.config/etc/ssl:/etc/nginx/ssl
      - ./.config/etc/admin-moskvatrip-ru.conf:/etc/nginx/service-admin-moskvatrip-ru.conf
      - ./.config/etc/admin-nevatrip-ru.conf:/etc/nginx/service-admin-nevatrip-ru.conf
      - ./.config/etc/admin-prahatrip-cz.conf:/etc/nginx/service-admin-prahatrip-cz.conf
      - ./static:/srv/docroot
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=tech-support@nevatrip.ru
      - LE_FQDN=admin.moskvatrip.ru,admin.nevatrip.ru,admin.prahatrip.cz
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
