name: Docker Images Publish

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Build Images
      env:
        YC_REGISTRY_ID: crpfp7e90ctln8vulbiu
        IMAGE_TAG: ${GITHUB_REF##*/}
      run: docker-compose build
    - name: Publish the Docker Images to YC
      env:
        YC_OAUTH: AgAAAAASc26lAATuwb4k-nWW3EvTmHZOMpsAwNE
      run: |
        docker login --username oauth --password ${YC_OAUTH} cr.yandex
        docker-compose push
