# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  [push]
#   push:
#     branches:
#       - master
#       - develop
#       - test

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}

    - name: Login
      run: docker login --username oauth --password ${{ secrets.YC_OAUTH }} cr.yandex

    - name: Build
      run: docker build . -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/admin:${GITHUB_REF##*/}

    - name: Push
      run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/admin:${GITHUB_REF##*/}
